server:
  port: ${SERVER_PORT}

logging:
  level:
    root: ${HOST_ME_SERVICE_ROOT_LOG_LEVEL}
    com.di: DEBUG
    org.jooq: INFO
  config: ${LOGBACK_CONFIG_FILE:classpath:logback-spring.xml}

spring:
  application.name: ${APPLICATION_NAME:host-me-service}
  datasource:
    driver-class-name: "org.postgresql.Driver"
    jdbcUrl: ${DB_CONNECTION_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    default-schema: ${DB_SCHEMA}
    hikari:
      jdbc-url: ${DB_CONNECTION_URI}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jooq:
    sql-dialect: POSTGRES
    schema-name: ${DB_SCHEMA}
  liquibase:
    url: ${DB_CONNECTION_URI}
    user: ${DB_LIQUIBASE_USERNAME}
    password: ${DB_LIQUIBASE_PASSWORD}
    default-schema: ${DB_SCHEMA}
    parameters:
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USERNAME: ${DB_USERNAME}

springdoc:
  swagger-ui:
    disable-swagger-default-url: true